### ISSUE TITLE
 Ldap Authentication is disabled for given tenant (id:1)! You can enable it by setting 'Abp.Zero.Ldap.IsEnabled' to true

### ISSUE THREAD

**Issue by nandaccio** [aspnetboilerplate/module-zero-forsaken#299]
I'm experiencing an unexpected behaviour with the following stub method:

````C#
  public override async Task<bool> TryAuthenticateAsync(string userNameOrEmailAddress, string plainPassword, Tenant tenant)
        {
            // TODO: implement the authorization logic 
            /*Base DN = "DC=region,DC=intra,DC=dummy,DC=com" 
                Server name = "servername.region.intra.dummy.com" 
                Alternate server name = "servername2.region.intra.dummy.com" 
                TCP Port = 3268 (global catalog) */
            return true;
        }
````

It after returning it generates the following exception:

````
ERROR 2017-02-09 13:29:55,367 [12   ] XXX.Web.Controllers.AccountController - Ldap Authentication is disabled for given tenant (id:1)! You can enable it by setting 'Abp.Zero.Ldap.IsEnabled' to true
Abp.AbpException: Ldap Authentication is disabled for given tenant (id:1)! You can enable it by setting 'Abp.Zero.Ldap.IsEnabled' to true
   at Abp.Zero.Ldap.Authentication.LdapAuthenticationSource`2.<CheckIsEnabled>d__12.MoveNext() in D:\Halil\Github\module-zero\src\Abp.Zero.Ldap\Ldap\Authentication\LdapAuthenticationSource.cs:line 140
````

But:
- MultiTenancy is disabled (I commented out Configuration.MultiTenancy.IsEnabled)
-  Configuration.Modules.ZeroLdap().IsEnabled; is TRUE
-  The following records have been added to AbpSettings:

````
TenantID	Name	Value
NULL	Abp.Zero.Ldap.IsEnabled	true
1	Abp.Zero.Ldap.IsEnabled	true
````

- In the account controller, GetLoginResultAsync is invoked with  loginModel.TenancyName = null (by default)

What could cause the exception?

**Comment by nandaccio** [comment]
Update, I changed my test code to:

    public class DummyLDAPAuthenticationSource : LdapAuthenticationSource<Tenant, User>
    {
        private readonly ILdapSettings _settings;
        private readonly IAbpZeroLdapModuleConfig _ldapModuleConfig;

        public DummyLDAPAuthenticationSource(ILdapSettings settings, IAbpZeroLdapModuleConfig ldapModuleConfig)
            : base(settings, ldapModuleConfig)
        {
            _settings = settings;
            _ldapModuleConfig = ldapModuleConfig;
        }

        public override async Task<bool> TryAuthenticateAsync(string userNameOrEmailAddress, string plainPassword, Tenant tenant)
        {
            // TODO: implement the authorization logic 
            /*Base DN = "DC=region,DC=intra,DC=dummy,DC=com" 
                Server name = "servername.region.intra.dummy.com" 
                Alternate server name = "servername2.region.intra.dummy.com" 
                TCP Port = 3268 (global catalog) */

            if (!_ldapModuleConfig.IsEnabled || !(await _settings.GetIsEnabled(GetIdOrNull(tenant))))
            {
                return false;
            }

            using (var principalContext = await CreatePrincipalContext(tenant))
            {
                return true;
            }
        }

and now the exception is:

ERROR 2017-02-09 14:30:55,542 [11   ] Dummy.Web.Controllers.AccountController - The specified directory service attribute or value does not exist.

System.Runtime.InteropServices.COMException (0x8007200A): The specified directory service attribute or value does not exist.

   at System.DirectoryServices.DirectoryEntry.Bind(Boolean throwIfFail)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_SchemaEntry()
   at System.DirectoryServices.AccountManagement.ADStoreCtx.IsContainer(DirectoryEntry de)
   at System.DirectoryServices.AccountManagement.ADStoreCtx..ctor(DirectoryEntry ctxBase, Boolean ownCtxBase, String username, String password, ContextOptions options)
   at System.DirectoryServices.AccountManagement.PrincipalContext.CreateContextFromDirectoryEntry(DirectoryEntry entry)
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoLDAPDirectoryInitNoContainer()
   at System.DirectoryServices.AccountManagement.PrincipalContext.DoDomainInit()
   at System.DirectoryServices.AccountManagement.PrincipalContext.Initialize()
   at System.DirectoryServices.AccountManagement.PrincipalContext.get_QueryCtx()
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithTypeHelper(PrincipalContext context, Type principalType, Nullable`1 identityType, String identityValue, DateTime refDate)
   at System.DirectoryServices.AccountManagement.Principal.FindByIdentityWithType(PrincipalContext context, Type principalType, String identityValue)
   at System.DirectoryServices.AccountManagement.UserPrincipal.FindByIdentity(PrincipalContext context, String identityValue)
   at Abp.Zero.Ldap.Authentication.LdapAuthenticationSource`2.<UpdateUserAsync>d__8.MoveNext() in D:\Halil\Github\module-zero\src\Abp.Zero.Ldap\Ldap\Authentication\LdapAuthenticationSource.cs:line 88

So I guess that LoginAsyncInternal must be overridden too.

**Comment by hikalkan** [comment]
I could not understand much. But LdapAuthenticationSource is very simple. You can just copy all code and customize it yourself for your own needs.
